version: "3.9"
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    ports: 
      - "6379:6379"
    networks:
      - "web.network"
    volumes:
      - redis_data:/data
  web:
    build: .
    image: mycontainerregistry06.azurecr.io/bitsnip
    container_name: "bitsnip"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    restart: "always"
    environment:
      - Replica= {{.Task.Name}}
    depends_on:
      - redis
    networks:
      - "web.network"
    deploy:
      replicas: 1
networks:
  web.network:
volumes:
  redis_data:
    driver: local